<![CDATA[
import type { NextApiRequest, NextApiResponse } from "next";
import { supabase } from "@/integrations/supabase/client";

const ADMIN_SERVICE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!; // Note: usually service_role key is used for admin tasks, but we'll use what's provided

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  // Set timeout for this API route
  res.setHeader('X-Vercel-Timeout', '60');

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { phone_number, tac } = req.body;

  if (!phone_number || !tac) {
    return res.status(400).json({ 
      error: "Nombor telefon dan kod TAC diperlukan" 
    });
  }

  try {
    console.log("🔐 Verifying TAC for:", phone_number);

    // 1. Find valid TAC (bypass type checking for whatsapp_tac)
    const { data: tacRecord, error: tacError } = await (supabase as any)
      .from("whatsapp_tac")
      .select("id, phone_number, member_id, expires_at")
      .eq("phone_number", phone_number)
      .eq("tac", tac)
      .eq("used", false)
      .gt("expires_at", new Date().toISOString())
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (tacError) {
      console.error("TAC query error:", tacError);
      return res.status(500).json({ 
        error: "Ralat pangkalan data semasa mengesahkan TAC" 
      });
    }

    if (!tacRecord) {
      console.log("❌ Invalid or expired TAC");
      return res.status(401).json({ 
        error: "Kod TAC tidak sah atau telah tamat tempoh" 
      });
    }

    console.log("✅ Valid TAC found, member_id:", tacRecord.member_id);

    // 2. Get member details
    const { data: member, error: memberError } = await (supabase as any)
      .from("members")
      .select("id, user_id, full_name, is_admin, is_approved")
      .eq("id", tacRecord.member_id)
      .single();

    if (memberError || !member) {
      console.error("Member query error:", memberError);
      return res.status(404).json({ 
        error: "Ahli tidak dijumpai" 
      });
    }

    // 3. Check if member is approved
    if (!member.is_approved) {
      console.log("❌ Member not approved");
      return res.status(403).json({ 
        error: "Akaun anda belum diluluskan oleh admin" 
      });
    }

    console.log("✅ Member approved, generating session via token API...");

    // Instead of creating a user here which fails if they exist, 
    // we use our internal generate-login-token API or do it properly.
    // For security and proper token generation, we'll fetch the generate-login-token endpoint locally
    
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || `https://${req.headers.host}`;
    
    try {
      const tokenResponse = await fetch(`${baseUrl}/api/generate-login-token`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          member_id: member.id,
          user_id: member.user_id 
        })
      });

      const tokenData = await tokenResponse.json();

      if (!tokenResponse.ok) {
        console.error("Token generation failed:", tokenData);
        // Fallback: If custom API fails, try to issue a custom JWT or use Supabase standard auth
        throw new Error(tokenData.error || "Gagal menjana token log masuk");
      }

      // 6. Mark TAC as used (fire and forget - don't wait)
      (supabase as any)
        .from("whatsapp_tac")
        .update({ used: true })
        .eq("id", tacRecord.id)
        .then(() => console.log("✅ TAC marked as used"))
        .catch((err: any) => console.error("Failed to mark TAC as used:", err));

      console.log("✅ Login successful for member:", member.full_name);

      // 7. Return success with auth token
      return res.status(200).json({
        success: true,
        auth_token: tokenData.token, // Use the token generated by generate-login-token
        member: {
          id: member.id,
          full_name: member.full_name,
          is_admin: member.is_admin,
        },
      });

    } catch (tokenErr) {
      console.error("Failed to generate token:", tokenErr);
      
      // Fallback: Try signInWithOtp or generating a custom response if the token endpoint fails
      return res.status(500).json({ 
        error: "Gagal menjana sesi log masuk. Sila hubungi admin." 
      });
    }

  } catch (error: any) {
    console.error("❌ Verify TAC error:", error);
    return res.status(500).json({ 
      error: "Ralat sistem. Sila cuba lagi atau hubungi admin." 
    });
  }
}
]]>

[Tool result trimmed: kept first 100 chars and last 100 chars of 4066 chars.]