-- Step 1: Drop old integer columns
ALTER TABLE training_scores
DROP COLUMN IF EXISTS frame1,
DROP COLUMN IF EXISTS frame2,
DROP COLUMN IF EXISTS frame3,
DROP COLUMN IF EXISTS frame4,
DROP COLUMN IF EXISTS frame5,
DROP COLUMN IF EXISTS frame6,
DROP COLUMN IF EXISTS frame7,
DROP COLUMN IF EXISTS frame8,
DROP COLUMN IF EXISTS frame9,
DROP COLUMN IF EXISTS frame10;

-- Step 2: Add text columns for every possible roll
ALTER TABLE training_scores
ADD COLUMN frame1_roll1 VARCHAR(1) NULL,
ADD COLUMN frame1_roll2 VARCHAR(1) NULL,
ADD COLUMN frame2_roll1 VARCHAR(1) NULL,
ADD COLUMN frame2_roll2 VARCHAR(1) NULL,
ADD COLUMN frame3_roll1 VARCHAR(1) NULL,
ADD COLUMN frame3_roll2 VARCHAR(1) NULL,
ADD COLUMN frame4_roll1 VARCHAR(1) NULL,
ADD COLUMN frame4_roll2 VARCHAR(1) NULL,
ADD COLUMN frame5_roll1 VARCHAR(1) NULL,
ADD COLUMN frame5_roll2 VARCHAR(1) NULL,
ADD COLUMN frame6_roll1 VARCHAR(1) NULL,
ADD COLUMN frame6_roll2 VARCHAR(1) NULL,
ADD COLUMN frame7_roll1 VARCHAR(1) NULL,
ADD COLUMN frame7_roll2 VARCHAR(1) NULL,
ADD COLUMN frame8_roll1 VARCHAR(1) NULL,
ADD COLUMN frame8_roll2 VARCHAR(1) NULL,
ADD COLUMN frame9_roll1 VARCHAR(1) NULL,
ADD COLUMN frame9_roll2 VARCHAR(1) NULL,
ADD COLUMN frame10_roll1 VARCHAR(1) NULL,
ADD COLUMN frame10_roll2 VARCHAR(1) NULL,
ADD COLUMN frame10_roll3 VARCHAR(1) NULL;